# Allows hydra to open up in the original folder of the run
defaults:
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

datasets:
 - events_selected_3311.h5

# The name of the model to export
network_name: stop_models_small
project_name: stops_nu2flows_small
batch_size: 1024
