# Allows hydra to open up in the original folder of the run
defaults:
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

datasets:
  # - events_selected_851.h5
  # - events_selected_769.h5
  # - events_selected_1355.h5
  # - events_selected_263.h5
  # - events_selected_2475.h5
  # - events_selected_728.h5
  # - events_selected_2497.h5
  # - events_selected_2766.h5
  # - events_selected_1258.h5
  # - events_selected_1770.h5
  # - events_selected_3328.h5
  # - events_selected_1887.h5
  # - events_selected_95.h5
  # - events_selected_910.h5
  # - events_selected_3105.h5
  # - events_selected_2114.h5
  # - events_selected_582.h5
  # - events_selected_3288.h5
  # - events_selected_351.h5
  # - events_selected_998.h5
  # - events_selected_1724.h5
  # - events_selected_2249.h5
  # - events_selected_1720.h5
  - events_selected_1036.h5
  # - events_selected_3211.h5
  # - events_selected_2354.h5
  # - events_selected_2124.h5
  # - events_selected_489.h5
  # - events_selected_1597.h5
  # - events_selected_1099.h5
  # - events_selected_374.h5
  # - events_selected_3375.h5
  # - events_selected_2707.h5
  # - events_selected_2392.h5
  # - events_selected_463.h5
  # - events_selected_2660.h5
  # - events_selected_699.h5
  # - events_selected_2273.h5
  # - events_selected_747.h5
  # - events_selected_2505.h5
  # - events_selected_312.h5
  # - events_selected_396.h5
  # - events_selected_2939.h5
  # - events_selected_793.h5
  # - events_selected_332.h5
  # - events_selected_1559.h5
  # - events_selected_1415.h5
  # - events_selected_1652.h5
  # - events_selected_2211.h5
  # - events_selected_1439.h5
  # - events_selected_2406.h5
  # - events_selected_1179.h5
  # - events_selected_1998.h5
  # - events_selected_2081.h5
  # - events_selected_3101.h5
  # - events_selected_3066.h5
  # - events_selected_1717.h5
  # - events_selected_2648.h5
  # - events_selected_442.h5
  # - events_selected_3024.h5
  # - events_selected_444.h5
  # - events_selected_527.h5
  # - events_selected_1933.h5
  # - events_selected_42.h5
  # - events_selected_1264.h5
  # - events_selected_1423.h5
  # - events_selected_2746.h5
  # - events_selected_618.h5
  # - events_selected_2572.h5
  # - events_selected_2832.h5
  # - events_selected_2244.h5
  # - events_selected_1416.h5
  # - events_selected_53.h5
  # - events_selected_2685.h5
  # - events_selected_2390.h5

# The name of the model to export
project_name: stops_nu2flows_rename # Determines output directory path and wandb project
network_name: stop_models 
batch_size: 1024 #8401 #1024
